on: [push]

jobs:
  make_file:
    runs-on: ubuntu-latest
    name: A job to run diff commands
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Analysis action step
      uses: ./.github/actions/ClientCheck # Uses an action in RepoCheck
      id: make
