on: [push]

jobs:
  make_file:
    runs-on: ubuntu-latest
    name: A job to run diff commands
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0                                   # Fetches all history
        ref: ${{ github.event.pull_request.head.sha }}   # Get pull request HEAD instead of merge
    - name: Diff action step
      uses: ./.github/actions/RepoCheck # Uses an action in RepoCheck
      id: make
